# Generated by Django 4.2.9 on 2025-07-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_receipt_invoice_receipt_patient_receipt_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
