# Generated by Django 4.2.9 on 2025-07-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('payments', '0004_invoice_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='items',
            field=models.ManyToManyField(help_text='Items included in this receipt.', through='payments.ReceiptItem', to='inventory.inventoryitem'),
        ),
    ]
