# Generated by Django 4.2.9 on 2025-07-03 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_receipt_items'),
    ]

    operations = [
    ]
