# Generated by Django 4.2.9 on 2025-07-18 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dentist", "0001_initial"),
        ("appointment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="dentist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dentist.dentist",
            ),
        ),
    ]
