# Generated by Django 4.2.9 on 2025-07-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
