# Generated by Django 4.2.9 on 2025-07-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorytransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='available_stock',
            field=models.IntegerField(default=0),
        ),
    ]
